# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 036bb6cb4fd27bf5691f7f09254c57703550c95bf9f8c2c92a206b373b23fa3c106c210722c7f2c2bb74896def9c72db8a81f306855fe3e3b7e13aa18af35907

test:
  secret_key_base: 12b842f263b8d05d3b2fe3fc136113e66865db16fb1d1ac48b75423930b2a72ef0c8745996d9ebd6e95bcf909b44ce431221aaaecc597fe73d63c07e1e1d14e5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
